[package]
name = "day04"
version = "0.1.0"
authors = ["Gabriel Ricard <gabriel.ricard@gremlin.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
